
name: My Build Workflow
 
on:
  push:
    branches:
      - master
jobs:
  build-test:
    runs-on: ubuntu-latest
    container: node:14

    steps:
     - name: Check Node.js version
       run: node --version

     - name: Checkout code
       uses: actions/checkout@v3
       
     - name: Install node packeges
       run: npm install

     - name: Run node app
       run: node index.js
     
